### ISSUE TITLE
Hookbox 0.2.0 installation under OS X 10.6.3

### ISSUE THREAD

**Issue by jrobgood** [play-co/hookbox#18]
Hookbox 0.2.0 installation under OS X 10.6.3 fails thus:
- Using easy_install throws TypeError: reduce() of empty sequence with no initial value. Seems to be related to the os.walk issued in setup.py around line 53. Mucking around in iPython I get this:

In [44]: print(os.path.exists('hookbox/static'))
False
- Installing from source gets further but fails (naturally) in the absence of GCC.

Resolution: Install Snow Leopard / iPhone SDK and install again from source.

**Comment by mcarter** [comment]
Fixed the first half of this issue; still require xcode to build greenlet
