### ISSUE TITLE
Enabling hookbox to hold (web app) application data for each user

### ISSUE THREAD

**Issue by codeorca** [play-co/hookbox#19]
Presumably, many pages that implement hookbox will do so to allow their stateless, non-server web app (such as a web app written in php) to function something like a server by pushing updates (that are a result of connected users' interactions with the web app) to all other connected clients.

For example, in my particular app, client A interacts with the web app via standard ajax requests, and all other clients are apprised of client A's interactions via the web app calling hookbox's rest publish url. Each client's javascript then determines from the payload what action to take to represent/react to the update.

Currently, in order to update all users about a change in state for a particular user, if client A's score increases, the web app can make a rest publish to tell every client to update this user's score.

However, what happens when a new user enters the page/channel and we want to show that user all of the other user's current scores, or otherwise initialize that user to the current state of things in a different application? Since the web app is stateless, we have to query our persistent storage (MySQL) for the score of every user in the channel, or every pertinent setting, package it up, make a rest publish call, and have each user's javascript process it.

I propose that hookbox allow for arbitrary application data to be associated with each present user so that updating said information for users in the channel is trivial. If web app data could reside in a hash for each user in the channel, then that data would be accessible on the client side simply by referencing frame.user.<hashkey>

Getting the state for all users in the channel would be a matter of iterating over the array of present users (already made available by hoobox) and referencing a key in their hash. This would render unnecessary MySQL lookups of everything bearing on the state by the web app and additional javascript functions or switch cases. By allowing hookbox to store application data for each user in a hash for the duration of the session (which can be update or unset via a rest call), when a new user joins the channel, all of the information they might need to initialize the proper state of the application (client side) would be available from hookbox, rather than having to first query all of the information for each user from persistent storage via the stateless web app, send a rest publish, and then write client side js to iterate through it.

I know in my own use case that being able to update george.points from the web app via /rest?cmd=updateUser&user=George&key=points&value=10 and then have that data be available to users in the channel and all new users who enter the channel would greatly simplify the development of almost any multi-user application I would personally use hookbox to implement.

Thanks for reading!

**Comment by desmaj** [comment]
It sounds to me like what you want is a caching mechanism. I don't think this belongs in hookbox.

**Comment by codeorca** [comment]
Even when classifying it as such, if the feature served to greatly simplify development for many of hookbox's potential use cases, namely apps where connected users are aware of other connected users' interactions with the app (aka their status), wouldn't adding the feature be worth it if it could be implemented relatively easily?

You could then do:

conn.onSubscribe = function(channelName, _subscription) {
  subscription = _subscription;
  for(user in subscription.presence) {
    updateDisplay(presence[user], presence[user].points, presence[user].locationX, presence[user].locationY);
  }
}

In reality you would likely want to pass the user and access its hash from within a function such as updateDisplay(), but I accessed the hash here for illustrative purposes.

The alternative is to do a potentially massive SQL (or other persistent storage mechanism) lookup on the web app side to get all of the state information every time a new client connects or an existing client needs it. You would also have to write client side js so that each client could maintain state information for every connected client.

Things would be greatly simplified if hookbox, which is already maintaining information about the user's presence, could also maintain a few application specific attributes about the presence.

**Comment by mcarter** [comment]
This was implemented as channel.state (see the docs)
