### ISSUE TITLE
When you reload a hookbox enabled page in IE, JS onUnsubscribe() never fires for browser's previous expired user (works in FireFox and Chrome, though)

### ISSUE THREAD

**Issue by codeorca** [play-co/hookbox#34]
Hello,

When you reload a hookbox enabled page in FireFox or Chrome and thereby reconnect to hookbox you receive an onUnsubscribe() callback which notifies you that the connections previously established in the same browser have unsubscribed (timed out). However, that does not happen in IE.

This is an issue because IE users will inevitably reload their browsers and functionality that depends on who is present won't work properly for them.

Hookbox outputs this error as soon as you reload the hookbox enabled page via IE: 

http://pastebin.com/gxViiXHt

A minute after you reload IE, hookbox will evidently try to send the unsubscribe message but fail. Hookbox outputs this error:

Error with disconnect callback Invalid callback response, status=404 (/hookbox/disconnect)

(This error does not occur in FireFox or Chrome, and instead onUnsubscribe fires on account of the user who's connection was severed when the browser was reloaded)

Thanks so much for looking into this!

**Comment by codeorca** [comment]
Here is the firebug lite console output in IE after connecting to the hookbox enabled page and then reloading it 3 times:

http://pastebin.com/RF7rntHn

**Comment by mcarter** [comment]
fixed
