### ISSUE TITLE
ImportError: No module named output_wrapper

### ISSUE THREAD

**Issue by codeorca** [play-co/hookbox#35]
Hello,

I tried building and running the most recent version of hookbox from github, mcarter-hookbox-0d1af6c.zip, which appears to have a fix for a bug I reported. 

When I tried running it, though, it appears it cannot find a module it requires to start, output_wrapper. Here is a link to the error output:

http://pastebin.com/GdQtpstK

Thank you

**Comment by codeorca** [comment]
I also tries "easy_install hookbox" thinking that it might take care of any missing dependencies but it did not.

**Comment by mcarter** [comment]
fixed
