### ISSUE TITLE
no obvious way to sanitize data server side.

### ISSUE THREAD

**Issue by ergo** [play-co/hookbox#41]
I was unable to find a way to sanitize published data to prevent XSS attacks etc.

**Comment by mcarter** [comment]
What do you mean? 
First off, the data comes through as json. It isn't evaled or anything.

Regardless, you can use "override_payload" in your publish callback/webhook response to replace the payload with a new one.

**Comment by ergo** [comment]
yeah, it seems i want that, is it documented anywhere ?

**Comment by ergo** [comment]
ok found it
