### ISSUE TITLE
Documentation Problem - Publish via JS API

### ISSUE THREAD

**Issue by Xorlev** [play-co/hookbox#47]
In the JS API documentation, it is stated that one must call the `publish` method from the subscription object.

```
subscription.publish(42);
subscription.publish({foo: "bar"});
subscription.publish(null);
subscription.publish([1,2,3, {a: [4,5,6] });
```

However, subscriptions do not have a "publish" method, rather that is found in the connection handle.

```
conn.publish("mychannel", message);
```

**Comment by mcarter** [comment]
fixed in trunk.
