### ISSUE TITLE
Hosted Hookbox, mangling Payload Objects sent to Webhook

### ISSUE THREAD

**Issue by Xorlev** [play-co/hookbox#50]
It seems that the Hosted Hookbox parses the JSON from the payload, but then returns a print of the parsed JSON.

It's currently passing this to my callback: `{u'data': u'MyMessage', u'type': u'message'}`

The `u'data'` is clearly indicative of a dict being printed out rather than having `json.dumps()` called on it.

**Comment by hamax** [comment]
I think I've found the problem: hookbox/channel.py line 167
The payload used in the frame is not json (it's result from json.loads), the original parameter payload should be used instead.
payload = encoded_payload overwrites it

**Comment by MSch** [comment]
I would really love to have that fixed. It seems really easy.

**Comment by MSch** [comment]
Have a fix commited: http://github.com/msch/hookbox

**Comment by mcarter** [comment]
Pulled into mcarter/hookbox, Thanks! NOTE: this is not deployed on hosted hookbox yet.
