### ISSUE TITLE
create channel cb not called

### ISSUE THREAD

**Issue by sylvain261** [play-co/hookbox#55]
If I call subscribe on a non existing channel, the create_channel callback is never called.
Protocol.py call server.get_channel witch create the channel without any call back to the web application.
In fact, I don't know when this callback is used (except through the create channel rest api).

**Comment by mcarter** [comment]
I think you're right. line 267 of server.py should probably have needs_auth=True by default. I need to look and see what else that would affect though.

**Comment by mcarter** [comment]
pulled in fix from jordoh/hookbox, thanks!
