### ISSUE TITLE
Request for comments in my changes using Restkit

### ISSUE THREAD

**Issue by daxreyes** [play-co/hookbox#81]
Im trying to join the mailing list to post regarding my attempt to use restkit instead of httplib
This is in response to the email thread (httplib -> reskit enhancement (requesting programmer & patch) ) http://groups.google.com/group/hookbox/browse_thread/thread/10b13e122e93053a
Below are my changes
http://github.com/raikage/hookbox/compare/master...restkit

**Comment by mcarter** [comment]
Hello; not sure why you are having trouble with the mailing list. Let me know more details and I'll check it out for you.

This looks like a good start, thanks! Can you send me a pull request here on github? That lets me make comments about the code directly.

**Comment by daxreyes** [comment]
closing this as this is related to 
https://github.com/mcarter/hookbox/issues/closed#issue/82
